version: '3.7'
services:

  download_inputs:
    build: docker/
    image: dictionary_build_env
    volumes:
      - type: bind
        source: ..
        target: /workspace
    command: '/workspace/DictionaryPC/data/downloadInputs.sh'

  wiktionary_splitter:
    build: docker/
    image: dictionary_build_env
    volumes:
      - type: bind
        source: ..
        target: /workspace
    command: "bash -c 'cd /workspace/DictionaryPC && ./WiktionarySplitter.sh'"

  compile:
    build: docker/
    image: dictionary_build_env
    volumes:
      - type: bind
        source: ..
        target: /workspace
    command: "bash -c 'cd /workspace/DictionaryPC && ./compile.sh'"

  generate_dictionaries:
    build: docker/
    image: dictionary_build_env
    volumes:
      - type: bind
        source: ..
        target: /workspace
    command: "bash -c 'cd /workspace/DictionaryPC && ./generate_dictionaries.sh'"
