FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y \
         openjdk-11-jdk \
         libicu4j-49-java \
         junit \
         libxerces2-java \
         libcommons-lang3-java \
         libcommons-compress-java
